# Jekyll configuration
markdown: kramdown
# kramdown : markdown의 개조판.
#markdown에서 불편한 사항을 개선한 형태.

# MyData
owner:
  name: DongJun Kim
  avatar: photo.jpg
  bio:  "B.S in mechanical engineering"
  email:  rigel9327@gmail.com
# Social networking links used in footer. update and remove as you like.
  github: github.com/rigel9327

highlighter: rouge
# text highlighter로 rouge이용
# 2016.02월 이후로 syntax highlighter는 rouge만 지원.
# Pygments 사용불가.

paginate: 20
#작성한 모든 post를 하나의 페이지에 열거할 수 없으니
#pagination이 필요하고 몇개의 post를 하나의 page에서 보여줄 건지를 설정.

language: 'en-uk'
# 언어 설정

url: https://rigel9327.github.io
# Google Search Console에서 사용하는 sitemap.xml 생성시
# 이 url key값이 존재하지 않으면 sitemap.xml이 정상적으로 생성되지 않는다.
# 또한 disqus(댓글 시스템)을 이용하기 위해서도 필요
# 자신의 github page url을 입력
# ( https://your_github_id.github.io 형식 )

baseurl: /


# Website info
title: Keep memories to lose
# 자신의 blog title.

description: Back-end 학습 블로그
# blog home에 표시될 blog에 대한 전반적인 설명.

cover: assets/built/images/blog-cover1.jpg
# blog home에 표시될 blog cover image.

logo:
logo_dark:

favicon: assets/built/images/favicon.png
# favicon으로 사용할 image

production_url: https://rigel9327.github.io/
# 최종적으로 blog가 운영될 url

source_url: https://github.com/rigel9327/GitHubPageMaker/
# blogmaker(jekyll source folder)에 대한 github repository

# Social info
navigation: True
# Navigation bar link를 보여줄건지 여부

subscribers: True
# subscriber 기능을 사용할건지 여부
# 약간의 수정을 통해 subscriber 기능 대신 Lunr.js를 이용한 검색 기능으로 대체 사용
# 검색기능으로 대체하기 위해서 '_includes/subscribe-form.html' 파일의 수정이 필요.

twitter:
facebook:
# 만약 twitter와 facebook을 이용하면 username을 입력

# Disqus
disqus: True
disqus_shortname: xxxxxxxx
# disqus는 온라인 댓글 시스템, 댓글 기능을 사용하기 위해
# disqus를 이용할 것인지 여부와 만약 사용하면
# disqus shortname을 입력 ( disqus username이 아님 )

# Google Analytics
google_analytics: UA-xxxxxxxx-x # replace with your GA tracking identifier
# Google Analytics를 사용할 경우 GA tracking identifier를 입력

# Permalinks
permalink: /:title
# permalink: /author/:author
# permalink: /tag/:title
# 각각의 post에 고정주소를 어떤 방식으로 할당할 것인지를 결정
# 이 값을 바꾸면 작성한 포스트의 저장위치나 파일이름이 변경된다.

# gems and other configs
plugins: [jekyll-paginate, jekyll-feed, jekyll-gist, jekyll-sitemap]

feed:
  path: feed.xml

# Travis-CI 설정입니다.
safe: False
Isi: False

username: rigel9327
repo: GitHubPageMaker
# username : travis-ci와 연동하는 github의 username
# repo : travis-ci와 연동하는 github의 repository 이름
# https://github.com/<username>/<repository>

branch: master
# 사용할 branch먕

relative_source:

destination: ../[GitHubPage]/
# compile된 결과가 생성되는 폴더
# 이 폴더 안의 내용이 우리가 운영하는 블로그 내용이 컴파일 돼서 들어간다.
# 이 폴더 안의 내용을 github repository(https://username.github.io)에 push
# 만약 Travis-CI를 이용할 예정이라면 이 부분을 git submodule로
# github repository(https://username.github.io)에 연결해야 한다.

# exclude는 jekyll 컴파일 시 destination에 포함될 필요가
# 없는 것들을 명시한다. (node_modules와 필요없는 것들은 제외)
exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - node_modules
  - assets/css
  - assets/images
  - _posts/angular
  - _posts/et-cetera
#  - _posts/python
  - _posts/typescript
#  - _posts/jekyll
  - _posts/iot
  - _posts/r
  - _posts/economy
